version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db:/var/lib/postgresql/data

  webserver:
    build:
      context: ../..
      dockerfile: deploy/airflow/Dockerfile.airflow
    image: my-airflow-toml:latest
    depends_on:
      - postgres
      - mlflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/src
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ../../src:/opt/airflow/src
      - ../../data:/opt/airflow/data
      - ../../models:/opt/airflow/models
    entrypoint: [ "airflow", "webserver" ]
    ports:
      - "8080:8080"

  scheduler:
    image: my-airflow-toml:latest
    depends_on:
      - webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/src
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ../../src:/opt/airflow/src
      - ../../data:/opt/airflow/data
      - ../../models:/opt/airflow/models
    entrypoint: [ "airflow", "scheduler" ]

  mlflow-db:
    image: postgres:15.8-alpine
    environment:
      POSTGRES_PASSWORD: mlflow
      POSTGRES_USER: mlflow
      POSTGRES_DB: mlflow
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mlflow" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mlflow-db:/var/lib/postgresql/data

  mlflow:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.mlflow
    environment:
      BACKEND_STORE_URI: postgresql+psycopg2://mlflow:mlflow@mlflow-db:5432/mlflow
      ARTIFACT_ROOT: file:/mlruns
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
    depends_on:
      mlflow-db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - mlflow-artifacts:/mlruns

volumes:
  postgres-db:
  mlflow-db:
  mlflow-artifacts:
