---
repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [--line-length=88]
        # NOTE: no change here—black will skip non‐py by default

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff-check
        args: [--fix]
        # only run on .py files
        files: \.py$
      - id: ruff-format
        # only run on .py files
        files: \.py$

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      - id: yamllint
        files: \.(yml|yaml)$
        exclude: ^(docs/|mlruns/|deploy/)              # exclude docs, mlruns and deploy
        args:
          - "-d"
          - >-
            {extends: default,
             rules: {line-length: {max: 120},
                     new-line-at-end-of-file: disable,
                     document-start: disable}}
